name: Build, lint & test

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: '/go'

      - name: Build
        run: make build

  lint:
    needs: [ build ]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: '/go'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          install-mode: binary

  test:
    needs: [ build ]
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: '/go'

      - name: Get total coverage
        run: |
          COVERAGE=$(go tool cover -func build/coverage.out | \
          grep --color=never "^total:" | \
          awk '{print substr($3, 1, length($3)-1)}')
          
          echo "coverage: $COVERAGE"
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT 

  generate_badge:
    needs: [ test ]
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Collect coverage info
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

          # Replace slashes with underscores
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/\//_/g')
          echo $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV


      - name: Generate Cover Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ vars.GIST_ID }}
          filename: ${{ env.REPO_NAME }}__${{ env.BRANCH_NAME }}.json
          label: Code coverage
          message: '${{ env.COVERAGE }}%'
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ needs.test.outputs.coverage }}
          namedLogo: go
