name: Go

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: ''

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Get total coverage
        run: |
          COVERAGE=$(go tool cover -func build/coverage.out | \
          grep --color=never "^total:" | \
          awk '{print substr($3, 1, length($3)-1)}')
          
          echo "coverage: $COVERAGE"
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          
          # Replace slashes with underscores
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/\//_/g')
          echo $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Generate Cover Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ vars.GIST_ID }}
          filename: ${{ env.REPO_NAME }}__${{ env.BRANCH_NAME }}.json
          label: Code coverage
          message: '${{ env.COVERAGE }}%'
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.COVERAGE }}
          namedLogo: go
